In [28]:
import pandas as pd
import numpy as np

In [29]:
def DTWDistance(s1, s2,w):
    DTW={}
    
    w = max(w, abs(len(s1)-len(s2)))
    
    for i in range(-1,len(s1)):
        for j in range(-1,len(s2)):
            DTW[(i, j)] = float('inf')
    DTW[(-1, -1)] = 0
  
    for i in range(len(s1)):
        for j in range(max(0, i-w), min(len(s2), i+w)):
            dist= (s1[i]-s2[j])**2
            DTW[(i, j)] = dist + min(DTW[(i-1, j)],DTW[(i, j-1)], DTW[(i-1, j-1)])
		
    return sqrt(DTW[len(s1)-1, len(s2)-1])

In [30]:
def LB_Keogh(s1,s2,r):
    LB_sum=0
    for ind,i in enumerate(s1):
        
        lower_bound=min(s2[(ind-r if ind-r>=0 else 0):(ind+r)])
        upper_bound=max(s2[(ind-r if ind-r>=0 else 0):(ind+r)])
        
        if i>upper_bound:
            LB_sum=LB_sum+(i-upper_bound)**2
        elif i<lower_bound:
            LB_sum=LB_sum+(i-lower_bound)**2
    
    return sqrt(LB_sum)

In [31]:
import random

def k_means_clust(data,num_clust,num_iter,w=5):
    centroids=random.sample(data,num_clust)
    counter=0
    for n in range(num_iter):
        counter+=1
        print (counter)
        assignments={}
        #assign data points to clusters
        for ind,i in enumerate(data):
            min_dist=float('inf')
            closest_clust=None
            for c_ind,j in enumerate(centroids):
                if LB_Keogh(i,j,5)<min_dist:
                    cur_dist=DTWDistance(i,j,w)
                    if cur_dist<min_dist:
                        min_dist=cur_dist
                        closest_clust=c_ind
            if closest_clust in assignments:
                assignments[closest_clust].append(ind)
            else:
                assignments[closest_clust]=[]
    
        #recalculate centroids of clusters
        for key in assignments:
            clust_sum=0
            for k in assignments[key]:
                clust_sum=clust_sum+data[k]
            centroids[key]=[m/len(assignments[key]) for m in clust_sum]
    
    return centroids

In [32]:
dir_origen_csv = "./CSV_generated/"
dir_export = "./Images_generated/"

In [33]:
file_name1 = dir_origen_csv + "Data_limpia_windows.csv"
df = pd.read_csv(file_name1, low_memory = False, sep=",")
df.head()

,medidor,fecha,lectura_id_orig,voltajeA,voltajeB,voltajeC,corrienteA,corrienteB,corrienteC,modelo,...,Longitud,CLASIFICACION,kwh_consumido,kvarh_consumido,tipo_consumo,clasificacion_encoded,modelo_encoded,tipo_consumo_encoded,kwh_hora,dayMonth
0,15029828,2019-04-04 01:00:58,1141410,117.4806,117.7270,117.3373,2.5937,0.4362,1.2456,A3,...,-79.4001,PILADORA,23.2575,0.0,medio,3,0,0,11.628750,14
1,15029828,2019-04-04 03:00:58,1141840,117.3321,117.5873,117.6078,2.5860,0.4373,1.2439,A3,...,-79.4001,PILADORA,22.6800,0.0,medio,3,0,0,11.340000,14
2,15029828,2019-04-04 05:00:58,1142271,118.3265,118.3270,118.5901,2.6232,0.4349,1.2502,A3,...,-79.4001,PILADORA,23.5200,0.0,medio,3,0,0,11.760000,14
3,15029828,2019-04-04 07:01:01,1142711,119.8214,119.9720,119.6614,2.6989,0.4356,1.2671,A3,...,-79.4001,PILADORA,20.2125,0.0,medio,3,0,0,10.102041,14
4,15029828,2019-04-04 09:01:02,1143130,114.6726,114.8017,115.2943,2.0728,0.8169,0.9463,A3,...,-79.4001,PILADORA,26.4075,0.0,medio,3,0,0,13.201916,14

In [34]:
groups = df[["medidor", "kwh_consumido"]].groupby("medidor")

In [66]:
big_dict = {}
for n,g in groups:
    #big_dict[n] = []
    big_dict[n] = [g["kwh_consumido"].values]

In [67]:
'''
new_data = pd.DataFrame.from_dict(big_dict)
new_data
'''

'\nnew_data = pd.DataFrame.from_dict(big_dict)\nnew_data\n'

In [68]:
#big_dict.values()

In [69]:
import matplotlib.pylab as plt
data = np.array(big_dict.values())
centroids=k_means_clust(list(big_dict),4,10,4)
for i in centroids:
    
    plt.plot(i)

plt.show()

1

TypeError: 'int' object is not iterable

In [70]:
list(big_dict)

[15029828,
 15029835,
 15029844,
 15029846,
 15029847,
 15029974,
 15029977,
 15842884,
 15842885,
 15842894,
 15842921,
 16567733,
 16567738,
 16567740,
 16567743,
 16567746,
 16567753,
 16567757,
 16567758,
 16567759,
 16567760,
 16567761,
 16567762,
 16567763,
 16567764,
 16951175,
 16951176,
 16951177,
 16951179,
 16951180,
 16951181,
 16951182,
 16951195,
 16951199,
 16951201,
 16951203,
 16951205,
 16951206,
 16951207,
 16951208,
 16951209,
 16951210,
 16951212,
 16951216,
 16951219,
 16951220,
 16951221,
 16951222,
 17548289,
 20037205,
 20037214,
 20037228,
 28006904,
 28877074,
 35924863,
 35924864,
 35924866,
 35924882,
 35925134,
 35925291,
 35925294,
 35925308,
 35925506,
 35946575,
 35946920,
 35947180,
 35947190,
 41175730,
 52071420,
 52071428,
 52071447,
 52071455,
 52073163,
 52073194,
 52073196,
 52073198,
 52073200,
 52073201,
 52073218,
 52073240,
 52073259,
 52073264,
 52073290,
 52073292,
 52073295,
 52073302,
 52073321,
 52073331,
 52073345,
 52073348,
 52073352,
 52073359,
 52073382,
 53307830,
 53307859,
 53307861,
 53307871,
 53444735,
 58706632,
 58706634,
 58706655,
 58706656,
 58706659,
 58706662,
 58706663,
 58706704,
 58706706,
 58706709,
 58706713,
 58706725,
 58706740,
 59814806]